#!/usr/bin/python
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BOARD)

GPIO.setup(7, GPIO.OUT)
GPIO.setup(19, GPIO.IN)

try:
    while (True):
        if (GPIO.input(19)):
	    print("Button Pressed")
	    GPIO.output(7, True)
	    time.sleep(0.2)

except KeyboardInterrupt:
    print("Shutting down program and disabling pins")
    GPIO.cleanup()
