#!/usr/bin/python

import RPi.GPIO as GPIO
import time
from datetime import timedelta

GPIO.setmode(GPIO.BOARD)

alarmActivated = False

#ultrasoon
TRIG = 11
ECHO = 7
GPIO.setup(TRIG, GPIO.OUT)
GPIO.setup(ECHO, GPIO.IN)

#led
led = 13
GPIO.setup(led, GPIO.OUT)
GPIO.output(led, False)

#button
button = 15
GPIO.setup(button, GPIO.IN, pull_up_down=GPIO.PUD_UP)

def alarmListen():
    GPIO.output(TRIG, False)
    time.sleep(0.2)
    GPIO.output(TRIG, True)
    time.sleep(0.00001)
    GPIO.output(TRIG, False)
    while GPIO.input(ECHO) == 0:
        pulse_start = time.time()
    while GPIO.input(ECHO) == 1:
        pulse_end = time.time()
    pulse_duration = pulse_end - pulse_start
    distance = pulse_duration * 17150
    distance = round(distance, 2)
    if (distance <= 10):
	alarmActivated = True
    print(alarmActivated)

def activateAlarm():
    alarmActivated = True
    setLed(True)
    writeLogFile()

def setLed(on):
    if (on == True):
	GPIO.output(led, True)
	time.sleep(0.5)
	GPIO.output(led, False)
	time.sleep(0.5)
    else:
	GPIO.output(led, False)

def writeLogFile():
    print("write to log file")

def resetAlarm(self):
    alarmActivated = False
    setLed(False)

GPIO.add_event_detect(button, GPIO.FALLING, callback=resetAlarm, bouncetime=300)

try:
   while(True):
	if (alarmActivated == False):
	    alarmListen()	
        else:
	    activateAlarm()

except KeyboardInterrupt:
    print("exiting program")
    GPIO.cleanup()

